[package]
name = "askew"
version = "0.1.0"
authors = ["Piotr Dobiech"]
edition = "2021"
description = "Curves editor"

[dependencies]
anyhow = "1.0.71"
atoi = "2.0.0"
fontdue = "0.7.3"
log = "0.4.19"
num-traits = "0.2.15"
rand = "0.8.5"
replace_with = "0.1.7"
thiserror = "1.0.40"
time = "0.3.22"

[dependencies.bytemuck]
version = "1.13.1"
features = ["derive"]

[dependencies.chumsky]
version = "0.9.2"
default-features = false
features = ["std"]

[dependencies.clap]
version = "4.3.3"
features = ["derive"]

[dependencies.image]
version = "0.24.6"
default-features = false
features = ["png"]

[dependencies.lru]
version = "0.10.0"
default-features = false

[dependencies.simplelog]
version = "0.12.1"
default-features = false
features = ["termcolor", "local-offset"]

[dependencies.softbuffer]
version = "0.3.0"
default-features = false
features = ["x11"]

[dependencies.tiny-skia]
version = "0.11.0"
default-features = false
features = ["std", "simd"]

[dependencies.winit]
version = "0.28.6"
default-features = false
features = ["x11"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "convex_hull"
harness = false

[[bench]]
name = "bezier"
harness = false
