[package]
name = "askew"
version = "0.1.0"
authors = ["Piotr Dobiech"]
edition = "2021"
description = "Curves editor"

[dependencies]
anyhow = "1.0.71"
bytemuck = "1.13.1"
fontdue = "0.7.3"
num-traits = "0.2.15"
rand = "0.8.5"
uninit = "0.5.1"

[dependencies.clap]
version = "4.3.1"
features = ["derive"]

[dependencies.image]
version = "0.24.6"
default-features = false
features = ["png"]

[dependencies.lru]
version = "0.10.0"
default-features = false

[dependencies.softbuffer]
version = "0.2.1"
default-features = false
features = ["x11"]

[dependencies.tiny-skia]
version = "0.10.0"
default-features = false
features = ["std", "simd"]

[dependencies.winit]
version = "0.28.6"
default-features = false
features = ["x11"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "convex_hull"
harness = false

[[bench]]
name = "bezier"
harness = false
