[package]
name = "askew"
version = "0.1.0"
authors = ["Piotr Dobiech"]
edition = "2021"

[dependencies]
anyhow = "1.0.70"
bytemuck = "1.13.1"
tiny-skia-path = "0.9.0"

[dependencies.clap]
version = "4.2.4"
features = ["derive"]

[dependencies.image]
version = "0.24.6"
default-features = false
features = ["png"]

[dependencies.softbuffer]
version = "0.2.0"
default-features = false
features = ["x11"]

[dependencies.tiny-skia]
version = "0.9.0"
default-features = false
features = ["std", "simd"]

[dependencies.winit]
version = "0.28.3"
default-features = false
features = ["x11"]
