package pitcer:askew

world askew {
  import curve: interface {
    type curve-id = u64

    get-position: func(id: curve-id) -> (horizontal: float32, vertical: float32)

    move-by: func(id: curve-id, horizontal: float32, vertical: float32)

    rotate-by: func(id: curve-id, angle-radians: float32)
  }

  import control: interface {
    sleep: func(seconds: u64, nanoseconds: u32)

    lock: func()

    unlock: func()
  }

  type run-argument = option<string>
  type run-result = result<option<string>, string>

  export run: func(argument: run-argument) -> run-result
}
